# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: install and run
    init: cd vr3f-template && yarn # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    command: yarn dev

 